ralphreid/w3d3/classwork/planets_app/config/routes.rb
# PlanetsApp::Application.routes.draw do

#   get '/plantes' => 'planets#index'  
#   get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit' #planet_edit_url, planet_edit_path methods are created by the helper
#   # so i could call planet_edt_path(@planet) would return a string
#   post '/planets/:id' => 'planets#update' #helper not needed because only the form uses this link
#   get '/planets/new' => 'planets#new', :as => 'new_planet'


#   # You can have the root of your site routed with "root"
#   # just remember to delete public/index.html.
#   root :to => 'planets#index'


PlanetsApp::Application.routes.draw do
 
  get    '/planets',          to: 'planets#index',  as: :planets
  post   '/planets',          to: 'planets#create'
  get    '/planets/new',      to: 'planets#new',    as: :new_planet
  get    '/planets/:id/edit', to: 'planets#edit',   as: :edit_planet
  get    '/planets/:id',      to: 'planets#show',   as: :planet
  put    '/planets/:id',      to: 'planets#update'
  delete '/planets/:id',      to: 'planets#destroy'
 
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
 
  root :to => 'planets#index'
 

end

ralphreid/w3d3/classwork/planets_app/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController 

  def index
    @planets = Planet.all
  end

  def new
    @planet = Planet.new
  end

  def create
    planet = Planet.new params[:planet]
    planet.save
    redirect_to planets_url
  end

  def show
    @planet = Planet.find params[:id]
  end

  def destroy
    Planet.find(params[:id]).destroy
    redirect_to planets_url
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    @planet = Planet.find params[:id]
    @planet.update_attributes(params[:planet])
    redirect_to @planet
  end

end

ralphreid/w3d3/classwork/planets_app/app/views/planets/_form.html.erb
<%= form_for(@planet) do |f| %>
  
  <fieldset>
    <legend>Planet Details</legend>

    <div class="field">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :image, 'Image URL' %>
      <%= f.url_field :image %>
    </div>

    <div class="field">
      <%= f.label :orbit, 'Orbit (AU)' %>
      <%= f.number_field :orbit, step: :any %>
    </div>

    <div class="field">
      <%= f.label :diameter, "Diameter (multiples of Earth's)" %>
      <%= f.number_field :diameter, step: :any %>
    </div>

      <div class="field">
      <%= f.label :mass, "Mass (multiples of Earth's)" %>
      <%= f.number_field :mass, step: :any %>
    </div>

    <div class="field">
      <%= f.label :moons, "Moons (count)" %>
      <%= f.number_field :diameter %>
    </div> 

    <div class="field">
      <%= f.label :planet_type, 'Planet Type' %>
      <% ['rocky', 'gas-giant'].each do |type| %>
        <%= f.radio_button :planet_type, type, checked: @planet.planet_type == type %>
        <%= f.label "planet_planet_type_#{type}", type, class: "checkbox-label" %>
      <% end %>
    </div>

    <div class="field">
      <%= f.label :rings, 'Rings?' %>
      <%= f.check_box :rings %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

  </fieldset>
<% end %>


   

ralphreid/w3d3/classwork/planets_app/app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form' %>

<br/>

<%= link_to 'Show', @planet %>
<%= link_to 'Back', planets_path %>

ralphreid/w3d3/classwork/planets_app/app/views/planets/index.html.erb
<% @planets.each do |planet| %>
  <p><%= link_to planet.name, planet_path(planet) %> has <%= pluralize(planet.moons, 'moon') %></p>

<% end %>

ralphreid/w3d3/classwork/planets_app/app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form' %>

<br/>

<%= link_to 'Back', planets_path %>

ralphreid/w3d3/classwork/planets_app/app/views/planets/show.html.erb
<h1><%= @planet.name %></h1>

<% if @planet.image.present? %>
  <%= image_tag @planet.image, class: "large-image" %>
<% end %>

<table>
  <tr>
    <th>Orbit</th>
    <td><%= @planet.orbit %> AU</td>
  </tr>

  <tr>
    <th>Diameter</th>
    <td><%= @planet.diameter %> Earth Diameters</td>
  </tr>

  <tr>
    <th>Mass</th>
    <td><%= @planet.mass %> Earth Masses</td>
  </tr>

  <tr>
    <th>Type</th>
    <td><%= @planet.planet_type %> Earth Masses</td>
  </tr>

  <tr>
    <th>Moons</th>
    <td><%= @planet.moons %></td>
  </tr>

  <tr>
    <th>Rings?</th>
    <td><%= @planet.rings %></td>
  </tr>

</table>

<nav>
  <%= link_to "Destroy this Planet", @planet, :method => :delete, :confirm => "Whoa there! Are sure you want to destroy #{@planet.name}?" %>
  |
  <%= link_to "Edit this planet", edit_planet_path(@planet) %>


</nav>